package exceptionhandling;

public class TryCatch2 {

	public static void main(String[] args) {

		
		try
		{
			int data=50/0;//throw exception
			
			
		}
		
		//handling exception
		
		catch(ArithmeticException e)
    
		{

		
		
		System.out.println("rest of the code");
	}

}
}
